config/routes.rb
Pinderhughes::Application.routes.draw do

  root to: 'pages#home'
  
  match '/about',    to: 'users#show',    via: 'get'
  match '/calendar', to: 'events#index',  via: 'get'
  match '/listen',   to: 'tracks#index',  via: 'get'
  match '/watch',    to: 'videos#index',  via: 'get'
  match '/news',     to: 'blogs#index',   via: 'get'
  # match '/contact',  to: 'pages#contact', via: 'get'

  devise_for :users
  
  resources  :blogs,  only: [:index, :show]
  resources  :events, only: [:index, :show]
  resources  :social_media_sites, only: [:index, :show] 
  resources  :tracks, only: [:index, :show]
  resources  :users,  only: [:show]
  resources  :videos, only: [:index, :show]

  get '/admin', to: 'admin/pages#home'
  namespace :admin do
    resources :blogs
    resources :events
    resources :social_media_sites
    resources :tracks
    resources :users
    resources :videos
  end
end

app/models/event.rb
class Event < ActiveRecord::Base

  validates :date_time, presence: true, in_the_future: true
  validates :venue, presence: true
  validates :user_id, presence: true

  belongs_to :user

  default_scope { order("date_time ASC") }
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController

  before_filter :load_events, only: [:edit, :update]
  before_filter :authorize
  
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id 
    if @event.save
      redirect_to admin_events_path, notice: 'event created'
    else
      render 'new', alert: 'not saved. try again'
    end 
  end

  def edit
  end

  def update
    if @event.update_attributes(event_params)
      redirect_to admin_events_path, notice: 'updates saved'
    else
      render 'edit', alert: 'updates not saved'
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    redirect_to admin_events_path, notice: 'event removed'
  end

  private
    def load_events
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:date_time, :link, :venue, :other_artists, :user_id)
    end
end

app/controllers/events_controller.rb
class EventsController < PagesController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/views/admin/events/edit.html.haml
%h1.row Update event
.row
  = form_for([:admin, @event],:html => { :method => :patch }) do |f|
    = f.datetime_field :date_time, placeholder: 'Date'
    = f.text_field :venue, placeholder: 'Venue'
    = f.text_field :other_artists, placeholder: 'Other Artists'
    = f.text_field :link, placeholder: 'Website Link'
    = f.submit "Save Update", class: 'button radius'

app/views/admin/events/index.html.haml
.row
  =link_to 'Add a new event', new_admin_event_path, class: 'button radius'
  - @events.each do |event|
    %h3
      = event.date_time.stamp('Jan 1, 2014')
      = render 'shared/index_of_objects', object: event
    = event.venue
    = "w/ #{event.other_artists}"
    = link_to 'Website', "#{event.link}"

app/views/admin/events/new.html.haml
%h1.row Add a new event
.row
  = form_for [:admin, @event] do |f|
    .errors
      - if @event.errors.any?
        %h4
          = pluralize(@event.errors.count, "error")
          prohibited this event from being saved:
        %ul.no-bullet
          - @event.errors.full_messages.each do |msg|
            %li= msg
    = f.text_field :date_time, placeholder: 'Date (required)'
    = f.text_field :venue, placeholder: 'Venue (required)'
    = f.text_field :other_artists, placeholder: 'Other Artists'
    = f.text_field :link, placeholder: 'Website Link'
    = f.submit 'Save', class: 'button radius'