config/routes.rb
Pinderhughes::Application.routes.draw do

  root to: 'pages#home'
  
  match '/about',    to: 'users#show',    via: 'get'
  match '/calendar', to: 'events#index',  via: 'get'
  match '/listen',   to: 'tracks#index',  via: 'get'
  match '/watch',    to: 'videos#index',  via: 'get'
  match '/news',     to: 'blogs#index',   via: 'get'
  # match '/contact',  to: 'pages#contact', via: 'get'

  devise_for :users
  
  resources  :blogs,  only: [:index, :show]
  resources  :events, only: [:index, :show]
  resources  :social_media_sites, only: [:index, :show] 
  resources  :tracks, only: [:index, :show]
  resources  :users,  only: [:show]
  resources  :videos, only: [:index, :show]

  get '/admin', to: 'admin/pages#home'
  namespace :admin do
    resources :blogs
    resources :events
    resources :social_media_sites
    resources :tracks
    resources :users
    resources :videos
  end
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  link       :string(255)
#  name       :string(255)
#  user_id    :integer
#  created_at :datetime
#  update_at  :datetime
#

class Track < ActiveRecord::Base

  validates :link, presence: true 
  validates :name, presence: true 
  validates :user_id, presence: true

  belongs_to :user

  def soundcloud_track_id(link)
    client = Soundcloud.new(client_id: "7740ceb86c3e214878ebdc0c7df4da6e")
    track_url = link
    track = client.get('/resolve', url: track_url)
    track.id
  end

end

app/controllers/admin/tracks_controller.rb
class Admin::TracksController < Admin::BaseController

  before_filter :load_track, only: [:edit, :update]
  before_filter :authorize
  
  def index
    @tracks = Track.all
  end

  def new
    @track = Track.new
  end

  def create
    @track = Track.new(track_params)
    @track.user_id = current_user.id
    if @track.save
      redirect_to admin_tracks_path, notice: 'track added'
    else
      render :new, alert: 'track not saved'
    end
  end

  def edit
  end

  def update
    if @track.update_attributes(track_params)
      redirect_to admin_tracks_path, notice: 'track updated'
    else
      render 'edit', alert: 'updates not saved'
    end
  end

  def destroy
    Track.find(params[:id]).destroy
    redirect_to admin_tracks_path, notice: 'track removed'
  end

  private
    def load_track
      @track = Track.find params[:id]
    end

    def track_params
      params.require(:track).permit(:link, :name, :user_id)
    end
end

app/controllers/tracks_controller.rb
class TracksController < PagesController
  def index
    @tracks = Track.all
  end

  def show
    @track = Track.find params[:id]
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
  def soundcloud_track_id(link)
    client = Soundcloud.new(client_id: ENV['SOUNDCLOUD_CLIENT_ID'])
    track_url = link
    track = client.get('/resolve', url: track_url)
    track.id
  end
end

app/views/admin/tracks/edit.html.haml
%h1.row Update track
.row
  = form_for([:admin, @track],:html => { :method => :patch }) do |f|
    = f.text_field :name, placeholder: 'Song Name'
    = f.text_field :link, placeholder: 'Soundcloud Link'
    = f.submit "Save Update", class: 'button radius'

app/views/admin/tracks/index.html.haml
.row
  =link_to 'Add a new soundcloud track', new_admin_track_path, class: 'button radius'

  - @tracks.each do |track|
    %h3
      = track.name
      = render 'shared/index_of_objects', object: track
    = render inline: track.link

app/views/admin/tracks/new.html.haml
%h1.row Add a new song track
.row
  = form_for [:admin, @track] do |f|
    = f.label      :name
    = f.text_field :name
    = f.label      :link
    = f.text_field :link
    = f.submit 'Save', class: 'button radius'