config/routes.rb
Pinderhughes::Application.routes.draw do

  root to: 'pages#home'
  
  match '/about',    to: 'users#show',    via: 'get'
  match '/calendar', to: 'events#index',  via: 'get'
  match '/listen',   to: 'tracks#index',  via: 'get'
  match '/watch',    to: 'videos#index',  via: 'get'
  match '/news',     to: 'blogs#index',   via: 'get'
  # match '/contact',  to: 'pages#contact', via: 'get'

  devise_for :users
  
  resources  :blogs,  only: [:index, :show]
  resources  :events, only: [:index, :show]
  resources  :social_media_sites, only: [:index, :show] 
  resources  :tracks, only: [:index, :show]
  resources  :users,  only: [:show]
  resources  :videos, only: [:index, :show]

  get '/admin', to: 'admin/pages#home'
  namespace :admin do
    resources :blogs
    resources :events
    resources :social_media_sites
    resources :tracks
    resources :users
    resources :videos
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  first_name             :string(255)
#  last_name              :string(255)
#  biography              :text
#  admin                  :boolean          default(TRUE)
#  primary                :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # TODO investigate why email and pw tests are not failing when
  # validation is commented out. most likely Devise is handling it      
  # validates :email, presence: true
  # validates :password, presence: true

  has_many :social_media_sites
  has_many :tracks
  has_many :events
  has_many :videos
  has_many :blogs

  def admin?
    admin
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  before_filter :load_users, only: [:show, :edit, :update]
  before_filter :authorize

  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to admin_path, notice: 'Profile updated.'
    else
      render 'edit', alert: 'update failed. try again'
    end
  end

  private 
    def load_users
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :biography, :email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < PagesController
  def show
    @user = User.where(primary: true).first
  end
end

app/views/admin/users/edit.html.haml
/ password editing handled by devise

%h1.row Update your info
.row.form
  = form_for([:admin, @user],:html => { :method => :patch }) do |f|
    = f.text_field :first_name, placeholder: 'First Name'
    = f.text_field :last_name, placeholder: 'Last Name'
    = f.email_field :email, placeholder: 'Email'
    = f.text_area  :biography, placeholder: 'Bio', rows: 15, cols: 1
    = f.submit "Save Update", class: 'button radius'

app/views/admin/users/index.html.haml
/is this necessary? possibly remove

/ TODO: new_user_registration_path only lets you sign up if you are
/ signed out but can't access the link if unless signed in.
/ if keeping users#index then fix

/ .row=link_to 'Add an admin', new_user_registration_path, class: 'button radius'

%ul.row
  - @users.each do |user|
    %li
      = user.first_name
      = user.last_name
      = user.email
      = link_to 'edit', edit_admin_user_path(user)
      = link_to 'remove', admin_user_path(user), method: :delete

app/views/admin/users/new.html.haml
this is users#new

app/views/admin/users/show.html.haml
%h3.row
  ="#{@user.first_name} #{@user.last_name}"
  %span.has-tip{"data-tooltip" => "", title: "edit"}
    = link_to edit_admin_user_path(@user) do
      = edit_icon
.row
  =@user.email
  %br
  %br
  %em
    = simple_format @user.biography