config/routes.rb
Pinderhughes::Application.routes.draw do

  root to: 'pages#home'
  
  match '/about',    to: 'users#show',    via: 'get'
  match '/calendar', to: 'events#index',  via: 'get'
  match '/listen',   to: 'tracks#index',  via: 'get'
  match '/watch',    to: 'videos#index',  via: 'get'
  match '/news',     to: 'blogs#index',   via: 'get'
  # match '/contact',  to: 'pages#contact', via: 'get'

  devise_for :users
  
  resources  :blogs,  only: [:index, :show]
  resources  :events, only: [:index, :show]
  resources  :social_media_sites, only: [:index, :show] 
  resources  :tracks, only: [:index, :show]
  resources  :users,  only: [:show]
  resources  :videos, only: [:index, :show]

  get '/admin', to: 'admin/pages#home'
  namespace :admin do
    resources :blogs
    resources :events
    resources :social_media_sites
    resources :tracks
    resources :users
    resources :videos
  end
end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  link       :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Video < ActiveRecord::Base
  
  validates :link, presence: true
  validates :user_id, presence: true

  belongs_to :user
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::BaseController
  
  before_filter :load_videos, only: [:edit, :update]
  before_filter :authorize

  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    @video.user_id = current_user.id
    if @video.save
      redirect_to admin_videos_path, notice: 'video link saved'
    else
      render 'new', alert: 'video link not saved'
    end
  end

  def edit
  end

  def update
    @video = Video.find(params[:id])
    if @video.update_attributes(video_params)
      redirect_to admin_videos_path, notice: 'video link updated'
    else
      render 'edit', alert: 'video link not updated. try again'
    end
  end

  def destroy
    Video.find(params[:id]).destroy
    redirect_to admin_videos_path, notice: 'video link removed'
  end

  private
    def load_videos
      @video = Video.find(params[:id])
    end
      
    def video_params
      params.require(:video).permit(:title, :link, :user_id)
    end
end

app/controllers/videos_controller.rb
class VideosController < PagesController
  def index
    @videos = Video.all
  end

  def show
    @video = Video.find(params[:id])
  end
end

app/helpers/videos_helper.rb
module VideosHelper
  def youtube_embed(link)
    link.sub!(/\A(https*:\/\/)/, '')
    link.prepend('//')
    link.sub(/(watch\?v=)/, 'embed/')
  end
end

app/views/admin/videos/edit.html.haml
%h1.row Update video
.row
  = form_for([:admin, @video],:html => { :method => :patch }) do |f|
    = f.text_field :title, placeholder: 'Title'
    = f.text_field :link, placeholder: 'Link'
    = f.submit "Save Update", class: 'button radius'

app/views/admin/videos/index.html.haml
.row
  =link_to 'Add a new video', new_admin_video_path, class: 'button radius'
  - @videos.each do |video|
    %h3
      = video.title
      = render 'shared/index_of_objects', object: video
    = render inline: video.link

app/views/admin/videos/new.html.haml
%h1.row Add a new song video
.row
  = form_for [:admin, @video] do |f|
    = f.text_field :title, placeholder: 'Title'
    = f.text_field :link, placeholder: 'Link'
    = f.submit 'Save', class: 'button radius'